# Generated by Django 3.2.25 on 2024-03-06 11:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('car_company', models.CharField(max_length=255)),
                ('car_model', models.CharField(max_length=255)),
                ('car_product_year', models.IntegerField()),
                ('other_details', models.CharField(max_length=255)),
                ('my_experience', models.TextField(blank=True)),
                ('car_image', models.ImageField(upload_to='pp5/images/cars')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
