# Generated by Django 3.2.25 on 2024-03-06 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20240306_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='production',
            field=models.IntegerField(choices=[], default=2024),
        ),
    ]
