# Generated by Django 3.2.25 on 2024-03-06 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_post_production'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='brand',
            field=models.CharField(choices=[('Toyota', 'Toyota'), ('Volkswagen', 'Volkswagen'), ('Audi', 'Audi'), ('Ford', 'Ford'), ('Honda', 'Honda'), ('BMW', 'BMW'), ('Mercedes-Benz', 'Mercedes-Benz'), ('Tesla', 'Tesla'), ('Chevrolet', 'Chevrolet'), ('Nissan', 'Nissan'), ('Hyundai', 'Hyundai'), ('Volvo', 'Volvo'), ('Mazda', 'Mazda'), ('Subaru', 'Subaru'), ('Kia', 'Kia'), ('renult', 'Renult'), ('porsche', 'Porsche'), ('Kia', 'Kia')], default='Toyota', max_length=255),
        ),
    ]
