# Generated by Django 3.2.25 on 2024-03-06 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_alter_post_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='brand',
            field=models.CharField(choices=[('toyota', 'Toyota'), ('volkswagen', 'Volkswagen'), ('audi', 'Audi'), ('ford', 'Ford'), ('honda', 'Honda'), ('bmw', 'BMW'), ('mercedes-Benz', 'Mercedes-Benz'), ('tesla', 'Tesla'), ('chevrolet', 'Chevrolet'), ('nissan', 'Nissan'), ('hyundai', 'Hyundai'), ('volvo', 'Volvo'), ('mazda', 'Mazda'), ('subaru', 'Subaru'), ('kia', 'Kia'), ('renult', 'Renult'), ('porsche', 'Porsche')], default='Toyota', max_length=255),
        ),
    ]
