# Generated by Django 3.2.25 on 2024-03-15 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20240315_1814'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='car_image',
            new_name='image',
        ),
    ]
