# Generated by Django 3.2.25 on 2024-03-16 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_rename_car_image_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.RemoveField(
            model_name='post',
            name='my_experience',
        ),
        migrations.RemoveField(
            model_name='post',
            name='other_details',
        ),
        migrations.RemoveField(
            model_name='post',
            name='production',
        ),
    ]
