# Generated by Django 3.2.25 on 2024-03-16 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_auto_20240316_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='pp5/images/cars'),
        ),
        migrations.AddField(
            model_name='post',
            name='my_experience',
            field=models.TextField(default='experience'),
        ),
        migrations.AddField(
            model_name='post',
            name='other_details',
            field=models.CharField(default='other details', max_length=260),
        ),
        migrations.AddField(
            model_name='post',
            name='production',
            field=models.IntegerField(default='2024'),
        ),
    ]
