# Generated by Django 3.2.25 on 2024-03-20 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_auto_20240316_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to='pp5/images/cars'),
        ),
        migrations.AlterField(
            model_name='post',
            name='my_experience',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='other_details',
            field=models.CharField(max_length=260),
        ),
        migrations.AlterField(
            model_name='post',
            name='production',
            field=models.IntegerField(),
        ),
    ]
