# Generated by Django 3.2.25 on 2024-03-20 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_auto_20240320_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='../default_post_rgq6aq', upload_to='pp5/images/cars'),
        ),
    ]
