# Generated by Django 3.2.25 on 2024-03-23 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0016_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='../tbgnrewxxoez16ofmvhg', upload_to='pp5/images/cars'),
        ),
    ]
