# Generated by Django 3.2.25 on 2024-03-05 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='../uc17ao5y4hftdcoz8kjq', upload_to='pp5/images/'),
        ),
    ]
