# Generated by Django 3.2.25 on 2024-03-06 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_rename_content_profile_about'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='name',
            new_name='profile_name',
        ),
        migrations.AddField(
            model_name='profile',
            name='favorite_car',
            field=models.TextField(blank=True),
        ),
    ]
