# Generated by Django 3.2.25 on 2024-03-08 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_alter_profile_favorite_car'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='profile_name',
            new_name='name',
        ),
    ]
