# Generated by Django 3.2.25 on 2024-03-22 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_rename_profile_name_profile_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='about',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='favorite_car',
        ),
    ]
