# Generated by Django 3.2.25 on 2024-03-22 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_auto_20240322_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='../scpevcha1fo1rxmc3f2o', upload_to='pp5/images/profile'),
        ),
    ]
