# Generated by Django 3.2.25 on 2024-03-21 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0005_comment_ratings_average'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='ratings_count',
        ),
    ]
