# Generated by Django 3.2.25 on 2024-03-21 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0006_remove_comment_ratings_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='ratings_average',
        ),
    ]
